Ext.define('Yihua.model.User', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'id', type: 'int'},
        { name: 'username', type: 'string'},
        { name: 'password', type: 'string'},
        { name: 'name', type: 'string'},
        { name: 'gender', type: 'string'},
        { name: 'identity', type: 'string'},
        { name: 'birthday', type: 'date'},
        { name: 'mobile', type: 'string'},
        { name: 'telephone', type: 'string'},
        { name: 'education', type: 'string'},
        { name: 'graduate_from', type: 'string'},
        { name: 'graduate_at', type: 'date'},
        { name: 'field', type: 'string'},
        { name: 'hired_field', type: 'string'},
        { name: 'title', type: 'string'},
        { name: 'registed_title', type: 'string'},
        { name: 'registed_at', type: 'date'},
        { name: 'promotion_alert_at', type: 'date'},
        { name: 'status', type: 'string'},
        { name: 'onboard_at', type: 'date'},
        { name: 'resign_at', type: 'date'},
        { name: 'work_status', type: 'string'},
        { name: 'contract_to', type: 'date'},
        { name: 'regular_at', type: 'date'},
        { name: 'comment', type: 'string'},
        { name: 'created_at', type: 'date'},
        { name: 'updated_at', type: 'date'},
        { name: 'email', type: 'string'},
        { name: 'manager_id', reference: 'Yihua.model.User'},
        { name: 'role_id', reference: 'Yihua.model.Role'},
        { name: 'snd_role_id', reference: 'Yihua.model.Role'},
        { name: 'salary_level_id', reference: 'Yihua.model.SalaryLevel'}
    ]
});